### PR TITLE
Move to using compressed JSON for Metadata

### PR DESCRIPTION
**Pull request by dmaclach**
This reduces the compiled size of the library by 75% and gets rid of a lot of support infrastructure. Instead of doing a pile of codegen the creates a class per country code, this uses the actual JSON as the backing metadata. It is imported into the application as compressed JSON. Overall this reduces the compiled binary size of libPhoneNumberiOS from 2.9 MB (ARM64/Arm7 compiled for profiling) down to 732k. It also makes updating the library significantly easier as it should only take updating the json file (and fixing any tests).

Sorry for the large patch, but it was difficult to break up into smaller pieces given the amount of change. All tests pass. If you accept this, we may want to consider dropping the iOS MetadataGenerator app as it basically doesn't do anything anymore, and we can just pull any of its tests into the test bundle.

### CODE REVIEW

**Comment by iziz** [comment]
Initially, the library was a structure that dynamically loaded from XML(plist)
To improve performance and optimize memory usage, we have changed the form to create a class that generates metadata.
So, I'm afraid "performance and memory usage".
Would you test that ? (and, travis has build error...)

**Comment by dmaclach** [comment]
Iziz, can you be more explicit about the performance constraints you are under? I have trouble seeing libPhoneNumber being a performance bottle neck for the majority of iOS applications. That being said I did do a profile. I build the Metadata app for both versions and ran them under the profiler (in release mode) on an iPhone SE. I removed lines 28-30 of AppDelegate.m so that it wasn't generating the source code. The results were that on first (and only first) access there was a 5ms difference as the data was expanded. Most of the hit was due to the json parsing (about 4 ms). After that there was no statistical performance difference between them. Interestingly since my version is 2.2 MB of executable binary vs the current version which is 4.9 MB of executable binary my version appeared to load about 3 ms faster due to less dyld overhead. So the actual difference was about 2ms on first access. Note that since I was using the profiling tool on a live device, that almost all of these samples are within error bars of each other. Note that my version has 0 disk hits, and I'm guessing the majority of the issues you may have been seeing with your plist version was due to the overhead of finding and loading the plist file. The decompression itself was < 1.0 ms.

I would like to believe that the majority of developers are actually more interested in reducing their overall binary size by a couple of megs rather than concerned about a possible one time hit of ~2 ms for phone number parsing.

The advantage for you is significantly less code to maintain.

Note that with further CLs I expect we can continue to reduce the binary size and memory usage once we have this basic framework in place. Do you have a performance/memory measurements that you feel you need to meet/beat? It appears to me that general regex generation is going to rapidly outweigh any of the performance hits you take with the one time load hit.

I'm sorry that my first version didn't pass Travis. Small oversight that I have remedied.

**Comment by hashier** [comment]
> I have trouble seeing libPhoneNumber being a performance bottle neck for the majority of iOS applications.

Just as a general note:
At my old company we often had to make tweaks of how to handle things because libPhoneNumber was often a bottle neck when we had to handle 10th of thousands of numbers and comparisons. (Not that this change would improve/worsen that since it is only the database, but generally speaking the lib does a lot which can often be a bottleneck for a phone number heavy application)

**Comment by dmaclach** [comment]
Fair enough. I should have been more explicit about the loading time being a performance impact to most applications. I don't suppose you remember where you ran into the most issues performance wise though do you?

**Comment by iziz** [comment]
> I removed lines 28-30 of AppDelegate.m so that it wasn't generating the source code.

Well, did you use that generate classes for your application in release stage ?
In fact, the actual classes are only for the Library Maintenance.
As you see below podspec, it is not part of library. and, I just wanted someone to update the metadata using that generate.
https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber-iOS.podspec

Please tell me, if I misunderstanding your PR.

**Comment by hashier** [comment]
> I don't suppose you remember where you ran into the most issues performance wise though do you?

Not directly with function it was, but it was when comparing two sets of phone numbers, one "clean" and one set user input phone numbers, so a lot of "cleaning", normalisation and parsing was needed. I think normalisation was always fine, but parsing phone numbers was super slow (when it needed to be done thousands of times on small phones likes iPhone 4).

We mostly ended up in just normalising phone numbers and comparing the last 7 digits and hoped for the best ;p

**Comment by dmaclach** [comment]
On Sat, Feb 11, 2017 at 12:08 AM, iziz <notifications@github.com> wrote:

> I removed lines 28-30 of AppDelegate.m so that it wasn't generating the
> source code.
>
> Well, did you use that generate classes for your application in release
> stage ?
> In fact, the actual classes are only for the Library Maintenance.
> As you see below podspec, it is not part of library. and, I just wanted
> someone to update the metadata using that generate.
> https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber-iOS.
> podspec
>
> Please tell me, if I misunderstanding your PR.
>

I removed those lines for the performance test because they would just
confuse the results.  I realize that they are only for library maintenance.
I was looking for some basic performance numbers and used the tests in the
iOS app to get some.

The point of my PR is to completely replace all of the generated code by
reading directly from the JSON data that is added to the binary as a gzip'd
blob.

See
https://github.com/iziz/libPhoneNumber-iOS/pull/175/files?diff=unified#diff-3e7193e5bdb678cf8fd5c04241b0fbfb
which
is the shell script that takes the JSON and creates a header that get
pulled into the binary.

**Comment by dmaclach** [comment]
>
> I don't suppose you remember where you ran into the most issues
> performance wise though do you?
>
> Not directly with function it was, but it was when comparing two sets of
> phone numbers, one "clean" and one set user input phone numbers, so a lot
> of "cleaning", normalisation and parsing was needed. I think normalisation
> was always fine, but parsing phone numbers was super slow (when it needed
> to be done thousands of times on small phones likes iPhone 4).
>
> We mostly ended up in just normalising phone numbers and comparing the
> last 7 digits and hoped for the best ;p
>

Understood. My change should have no effect on that.

**Comment by dmaclach** [comment]
Anymore thoughts on this Iziz? Not trying to be annoying, but we'd love to get it in.

**Comment by iziz** [comment]
Please wait :). I will test and merge this at this weekend.

**Comment by iziz** [comment]
I have some questions to this PR~
1. How can I update metadata from libphonenumber' metadata ?
2. How can I generate metadata? (real data & test data)

**Comment by dmaclach** [comment]
> 1. How can I update metadata from libphonenumber(googles) metadata ?
All you need to do is use the same process that you did previously to generate PhoneNumberMetaData.json and PhoneNumberMetaDataForTesting.json. The GeneratePhoneNumberHeader.sh reads directly from those files.
> 2. Maybe you can make shell script to fetch metadata from libphonenumber(googles)
Possibly. That would be a later PR. Right now your current system should work with no problems (and you won't have to run the MetadataGenerator app to get headers generated)
> 3. And, Hope to manage test metadata too (with compressed zip)
I do generate both test and standard Data which are added to PhoneNumberMetaData.h. The data that is actually compiled into the binary depends on the value of the TESTING macro (similar to how things worked previously). The test data does NOT get compressed into a release binary.
> 4. Does this PR has no issue for who use with CocoaPods & Carthage ?
I know of no reason that it should cause problems.
> 5. Is "PhoneNumberMetaData.h" always generate ? (derived data, clean, compile)
PhoneNumberMetaData will generate any time that:

1. PhoneNumberMetaData.h does not exist
2. PhoneNumberMetaData.h is older than GeneratePhoneNumberHeader.sh
3. PhoneNumberMetaData.h is older than PhoneNumberMetaData.json
4. PhoneNumberMetaData.h is older than PhoneNumberMetaDataForTesting.json

You can see how the dependencies are set up by looking at the Script phase of the GeneratePhoneNumberMetaDataHeader target.

**Comment by dmaclach** [comment]
soft ping :)

**Comment by iziz** [comment]
That *.json file is not part of library so it will not generate.

**Comment by dmaclach** [comment]
I'm sorry.. can you be more clear what you mean?

**Comment by iziz** [comment]
Ah, "PhoneNumberMetaData.json" file is not part of libPhoneNumber-iOS. So, your script will not execute well.

**Comment by dmaclach** [comment]
Sorry, still confused. I don't understand what you mean that PhoneNumberMetaData.json is not part of libPhoneNumber-iOS.

I am talking about these files 
https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumberTests/generatedJSON/PhoneNumberMetaData.json and
https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumberTests/generatedJSON/PhoneNumberMetaDataForTesting.json

They are the same files that you use to generate your metadata classes here:
https://github.com/iziz/libPhoneNumber-iOS/blob/master/libPhoneNumber/NBPhoneMetaDataGenerator.m#L160

The generation of these files doesn't need to change.

The file itself is read as part of the build steps in GeneratePhoneNumberHeader.sh , and is actually added directly to the compiled code as a compressed blob of data.

Could you please expand on your concerns? This really does shrink down the size of your binary without a negligible performance impact. I work for Google... it is in our best interest to have this library as small and efficient as possible.

**Comment by iziz** [comment]
I really want to merge your change. :)

Am I misunderstanding your PR ?

As you know "NBPhoneMetaDataGenerator.m" and it *.json files is just maintenance files for this library. 

- "GeneratePhoneNumberHeader.sh" will read from *.json and it will generate header file. 
   -> It seems maintenance stage. so that script file and json file will not include this library.

- But "NBMetadataHelper class" trying to read "PhoneNumberMetaData.h" file. and that header file doesn't exists in podspec and project.

**Comment by dmaclach** [comment]
Ahh.. the generation of PhoneNumberMetaData.h occurs as part of the build. So whenever people build the project, the header file will be generated at the right time based on the *.json files. There is no need to "ship" the json files anywhere, and no need to declare PhoneNumberMetaData.h in the podspec/project. Does that clarify? There is no "maintenance stage" at all anymore, other than updating the *.json files appropriately and when clients sync to head, and rebuild, they will get the latest data in their app.

**Comment by iziz** [comment]
Sorry, but I can't understand generate phase.
Please tell me your change from "AS-IS"

[AS-IS]
1. Generate JSON file from libphonenumber (web & PHP)
2. Generate Objective-C metadata code from JSON (NBPhoneMetaDataGenerator)
3. Commit & Push "Metadata class" to github (libPhoneNumber-iOS)
4. Update Cocoapods version.
5. People only use "generated matadata class code"

[TO-BE]
?

**Comment by dmaclach** [comment]
On Thu, Mar 2, 2017 at 18:09 iziz <notifications@github.com> wrote:

> Sorry, but I can't understand generate phase.
> Please tell me your change from "AS-IS"
>
> [AS-IS]
>
>    1. Generate JSON file from libphonenumber (web & PHP)
>    2. Generate Objective-C metadata code from JSON
>    (NBPhoneMetaDataGenerator)
>    3. Commit & Push "Metadata class" to github (libPhoneNumber-iOS)
>
> I assume you are committing the updated JSON file here as well.

>
>    1. Update Cocoapods version.
>    2. People only use "generated matadata class code"
>
> [TO-BE]
>

   1. Generate JSON file from libphonenumber (web & PHP)
   2. Commit & Push "json file" to github (libPhoneNumber-iOS)
   3. Update Cocoapods version.
   4. People get the updated data in their binary when they do their local
   build.

All that is happening here is that there is a build script step that reads
the JSON file and adds it as compressed data directly into the executable.
Thank you for doing due diligence on this. I think if you patch it in and
do a local build it should be clear what is going on.

**Comment by iziz** [comment]
>  I assume you are committing the updated JSON file here as well.
Yap, currently there is no "json file" for cocoapods / carthage.

So, I think you should modify "podfile" (for resource managing). and need description in "README.md" to 'how to add & run script' in their project.

**Comment by iziz** [comment]
or need another maintenance plan.

**Comment by dmaclach** [comment]
OK.. updated the PR with a new script that we will run.

1. Generate JSON file from libphonenumber (web & PHP)
2. Generate NBGeneratedPhoneNumberMetaData.h by running 'libPhoneNumber/GeneratePhoneNumberHeader.sh'
3. Commit & Push "json and header" to github (libPhoneNumber-iOS)
4. Update Cocoapods version.

Sorry for long delay. Been busy on other things.

**Comment by dmaclach** [comment]
This PR will fix https://github.com/iziz/libPhoneNumber-iOS/issues/170.

**Comment by dmaclach** [comment]
Thanks Iziz!

**Comment by iziz** [comment]
Great job.
But, I want to release this change, but here are some errors.

```
The following build commands failed:
	CompileC /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Intermediates/App.build/Release-appletvsimulator/App.build/Objects-normal/x86_64/main.o App/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> libPhoneNumber-iOS (0.9.5)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - ERROR | xcodebuild:  /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Products/Release-iphonesimulator/libPhoneNumber-iOS/libPhoneNumber_iOS.framework/Headers/NBGeneratedPhoneNumberMetaData.h:6:9: error: include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData' [-Werror,-Wnon-modular-include-in-framework-module]
    - NOTE  | xcodebuild:  /var/folders/vm/cqvyp6gn5jl5s_31vp8dl1pr0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'libPhoneNumber_iOS'
    - ERROR | [OSX] xcodebuild:  /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Products/Release/libPhoneNumber-iOS/libPhoneNumber_iOS.framework/Headers/NBGeneratedPhoneNumberMetaData.h:6:9: error: include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData' [-Werror,-Wnon-modular-include-in-framework-module]
    - ERROR | [watchOS] xcodebuild:  /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Products/Release-watchsimulator/libPhoneNumber-iOS/libPhoneNumber_iOS.framework/Headers/NBGeneratedPhoneNumberMetaData.h:6:9: error: include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData' [-Werror,-Wnon-modular-include-in-framework-module]
    - NOTE  | [watchOS] xcodebuild:  /var/folders/vm/cqvyp6gn5jl5s_31vp8dl1pr0000gn/T/CocoaPods/Lint/App/main.m:2:9: fatal error: could not build module 'libPhoneNumber_iOS'
    - ERROR | [tvOS] xcodebuild:  /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Products/Release-appletvsimulator/libPhoneNumber-iOS/libPhoneNumber_iOS.framework/Headers/NBGeneratedPhoneNumberMetaData.h:6:9: error: include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData' [-Werror,-Wnon-modular-include-in-framework-module]
```

"#include <zlib.h>" should be place in .m file.

**Comment by iziz** [comment]
Released (with some changes)

**Comment by iziz** [comment]
@dmaclach  Please check changes. (script, remove header and merge with m file)

**Comment by dmaclach** [comment]
@iziz I took a look.. I'm a little confused by what you are doing.

Why are you adding the NBGeneratedMetaData class?

**Comment by iziz** [comment]
Do you have any idea ? to remove "#include <libz.h>" to m file.

**Comment by iziz** [comment]
I just tried to remove "include of non-modular header inside framework module" error

**Comment by dmaclach** [comment]
How were you getting that error?

I'm building cleanly for iOS/tvOS/macOS/watchOS as far as I can tell (Xcode
8.3b3)

**Comment by iziz** [comment]
It only works locally.

I tested with below command, maybe you can't test it.
```
pod trunk push libPhoneNumber-iOS.podspec
```

**Comment by dmaclach** [comment]
Can you zip up the output you are seeing from that command and send it my
way?

**Comment by iziz** [comment]
Sorry, can't produce now.
So we should more test on this change to update via Cocoapods.
I will split code branch (oldway, newway)

**Comment by dmaclach** [comment]
OK.. if you can tell me how to repro, I'm happy to attempt to clean up.
There's got to be something easier than what you are doing.

Cheers,
Dave

**Comment by iziz** [comment]
Thanks, you can find your code in "newway" branch.

It's only a temporary expedient, but I will use "oldway".
- Revert with version 0.9.6

**Comment by dmaclach** [comment]
Hey there..

I think if you rewind all of your changes, and add:

spec.private_header_files =
'libPhoneNumber/NBGeneratedPhoneNumberMetaData.h'

to the podspec we should be ok...

You may want to move some other headers there to be private as well.

Cheers,
Dave

**Comment by iziz** [comment]
OK I will try.

**Comment by dmaclach** [comment]
Any luck?  If not, please supply me with any useful logs/repro etc so we can get this sorted out.

**Comment by iziz** [comment]
Not yet, but I can have time this coming Friday night.
And, I wanna keep your code as possible.

**Comment by dmaclach** [comment]
OK. Not trying to be annoying, just would like to get this in because I have projects waiting on it (both the size and performance improvements). Thanks!

**Comment by dmaclach** [comment]
Any luck?

**Comment by dmaclach** [comment]
Hey Iziz.. sorry to keep harping. I know I'm being a pain, but what can I do to help you get this sorted out? I think the line I gave you above will do what you want.

**Comment by dmaclach** [comment]
Checking in again. Have some other patches to send your way, but really need to get this one and pr-180settled first

**Comment by iziz** [comment]
I tried it, but it always fail :(

**Comment by iziz** [comment]
Sorry for late, I was very very very busy :(
It was applied to 0.9.7

**Pull request merged**
