### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by edwardmp**

### CODE REVIEW

**Comment by iziz** [comment]
Latest version is 0.8.2
Did I missed something ?

**Comment by edwardmp** [comment]
My previous pull request did not update the version number, hence CocoaPods not updating the pod.. so now I incremented the version number

**Comment by iziz** [comment]
This file will not include libPhoneNumber-iOS in cocoapods update. and your pull request will not affect to cocoapods.
Please tell me your purpose.

**Comment by edwardmp** [comment]
CocoaPods is now not detecting a new version, so when I run pods update this library is not updated.
I was confusing the proper way to issue a update with another dependency management system. For CocoaPods you should also create a new tag right? Could you do that?

**Comment by iziz** [comment]
As you see below, it works fine.
I think your issue comes from something else.

And Did you try remove all pod and reinstall it ?

```
$ pod update
Update all pods
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using AFNetworking (1.3.4)
Using SDWebImage (3.7.1)
Using TMCache (1.2.3)
Installing libPhoneNumber-iOS 0.8.2 (was 0.8.1)
Using pop (1.0.7)
Generating Pods project
Integrating client project

$ cat Podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PhoneNumberDevelopment' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 1.3.4'
pod 'SDWebImage', '~> 3.7'
pod 'TMCache', '~> 1.2.0'
pod 'pop', '~> 1.0'
pod 'libPhoneNumber-iOS', '~> 0.7'

end

target 'PhoneNumberDevelopmentTests' do

end
```

**Comment by edwardmp** [comment]
Nope, as you can see you are updating to version 0.8.2, which is the version you commited 10 days ago. 6 days ago you merged my previous pull request. Since the version number is not incremented and a new tag is not being created, the pod will not be updated..

**Comment by iziz** [comment]
No doubt! :) I did not create new version. All merged pull request will not affect right now. Normally, It would update once a month except critical error.

**Comment by edwardmp** [comment]
All right, then I will just wait to when you create a new tag. Was not sure if you want other people to update the version or not.

**Comment by iziz** [comment]
Anyway, I will create new version. (because variable initialization issue)

**Pull request closed without merging**
