### PR TITLE
Fixes up podspec so that it works properly, and adds a swift demo

### PR DESCRIPTION
**Pull request by dmaclach**
I tested the podspec with a local build, and it appears to function correctly. I am not a cocoapods expert by any means, but it should clean up the module problems. I also added a swift demo to make sure that swift was building correctly.

### CODE REVIEW

**Comment by iziz** [comment]
```
** BUILD FAILED **
The following build commands failed:
	CompileC /Users/zen.isis/Library/Developer/Xcode/DerivedData/App-eptqlzpdpfcjbeauawtjqnsalrpn/Build/Intermediates/Pods.build/Release-appletvsimulator/libPhoneNumber-iOS.build/Objects-normal/x86_64/NBMetadataHelper.o libPhoneNumber-iOS/libPhoneNumber/NBMetadataHelper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> libPhoneNumber-iOS (0.9.9)
    - ERROR | file patterns: The `private_header_files` pattern did not match any file.
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  libPhoneNumber-iOS/libPhoneNumber/NBMetadataHelper.m:11:9: fatal error: 'NBGeneratedPhoneNumberMetaData.h' file not found
```

**Comment by iziz** [comment]
So, I will rollback this~

**Comment by iziz** [comment]
You can test it with TAG (0.9.9) or Branch (EnhancedMetadata).
I will use LegacyMetadata branch until your solution comes up.

**Comment by dmaclach** [comment]
To be clear, I DID follow those steps, and it worked fine. How can I repro that error that you are seeing? Apparently Travis is building it cleanly and it's passing all tests. I can do a local use of cocoapods and it works fine. So what is interesting about how you are using it?

**Comment by iziz** [comment]
```
pod trunk push libPhoneNumber-iOS.podspec
```
and
you can test "pod trunk push testLib.podspec", if you have some pod (ex. TestLib)

**Pull request merged**
