### PR TITLE
TR: Allow numbers in format +90 (561) XXX XX XX

### PR DESCRIPTION
**Pull request by gokselkoksal**

### CODE REVIEW

**Comment by iziz** [comment]
Thanks, But this meta data file must be generate with google's meta data.
So, I will update it soon.

**Comment by gokselkoksal** [comment]
Right now we're using my fork in our project. Please leave this issue open so that we can switch back to your version once you update this with Google's metadata.

**Comment by iziz** [comment]
OK!

**Comment by iziz** [comment]
And, Could you leave some sample phone numbers to test validation ? (and its country code ex> US)

**Comment by gokselkoksal** [comment]
Sorry, you can reject the PR. :) I thought you closed the issue. I will provide test data on the issue.

**Pull request closed without merging**
