### PR TITLE
Dynamic framework target and Carthage support

### PR DESCRIPTION
**Pull request by marmelroy**
I saw this was attempted before but broke Cocoapods. To avoid that, I made no changes to the podspecs and they still work as expected. 

Readme is updated with Carthage instructions too.

### CODE REVIEW

**Comment by alikaragoz** [comment]
:+1:

**Comment by iziz** [comment]
Thank you !!!
As you know, it only available on iOS 8 or later.
So, Would you add "#ifdef (iOS8) ... #endif mark" code for iOS4~iOS7 ?

**Comment by marmelroy** [comment]
Indeed. 

It doesn't need the ifdef. The classic cocoapods target still has a deployment target of iOS 4.3 and still compiles. It's only the dynamic framework targets that has an iOS 8 target. 

(p.s. I did just notice however that my deployment target was 8.4 so changed it to 8.0)

**Comment by iziz** [comment]
Wonderful job!

**Pull request merged**
