### PR TITLE
Update meta data

### PR DESCRIPTION
**Pull request by meccatol**
I fixed also some failed test case.
When I fixed these, I referenced this info, https://github.com/google/libphonenumber/blob/master/resources/ShortNumberMetadata.xml .

(Hence it seems this repo need to update 'metadataGenerator' swift file to parse not json files but xml files.)

### CODE REVIEW

**Comment by meccatol** [comment]
@paween Thanks for murging it. :D 
Could you release newest version for us?

**Comment by lickel** [comment]
Hey @meccatol, do you know which version you ran this against?

We try to keep all our platforms in lockstep where I’m at. 

Also, what was the process to run the tool? It isn’t documented any where that I could find so I had taken a stab in the dark. 

Thanks!

**Comment by meccatol** [comment]
Hi @lickel, we used it with latest version, ''0.9.15'.
But this is out dated about a year! So I updated metadata for a newest version.

And I have dug this repo for updating metadata and found this issue, #258 . (It's helpful)
But some info is incorrect, so I followed next steps.

```zsh
$ cd yourFork/libPhoneNumberTests
$ swift metadataGenerator
(this is swift script file)
$ cd ../libPhoneNumber
$ ./GeneratePhoneNumberHeader.sh
```

Finally, I've got newest jsons and NBGeneratedPhoneNumberMetaData.h files.
And I figured out this repo use json files, but [original repo](https://github.com/google/libphonenumber) use xml file.

So I think it need to update 'metadataGenerator' script to use xml file to parse.

**Comment by lickel** [comment]
Do you remember which version you ran the `metadataGenerator` against for this PR?
Whatever was on master that day?

**Comment by meccatol** [comment]
I ran that script latest branch, master, commit sha is e50f018. (That time was 0.9.15 ver)

**Pull request merged**
